parameters:
- name: APPLICATION_VERSION
  type: string
  default: $(GitVersion.SemVer)
- name: CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME
  type: string
  default: ''
- name: DOCKER_BUILD_ARGS
  type: string
  default: '' #Exemplo: --build-arg FIRST_ARG=FIRST_ARG_VALUE --build-arg SECOND_ARG=SECOND_ARG_VALUE
- name: DOCKER_BUILD_CONTEXT_FOLDER
  type: string
  default: '$(Build.SourcesDirectory)'
- name: DOCKER_IMAGE_NAME
  type: string
  default: ''
- name: DOCKER_IMAGE_TAG
  type: string
  default: ''
- name: DOCKER_REGISTRY
  type: string
  default: ''
- name: DOCKERFILE_PATH
  type: string
  default: '$(Build.SourcesDirectory)/Dockerfile'
- name: EXECUTE_GITVERSION
  type: boolean
  default: true
- name: NODE_USED_VERSION
  type: string
  default: $(NODEJS_VERSION)
- name: PACKAGE_JSON_FILE_LOCATION
  type: string
  default: $(Build.SourcesDirectory)/package.json
- name: VM_IMAGE
  type: string
  default: '' # Exemplo: ubuntu-20.04



jobs:
  - job: build_job
    displayName: "Build"
    pool:
      vmImage: ubuntu-20.04
      demands:
        - java
    steps:
      - template: ../../shared/steps/checkout-repository.yml

      - template: ../shared/steps/use-specific-node-version.yml
        parameters:
          NODE_USED_VERSION: ${{ parameters.NODE_USED_VERSION }}

      - ${{ if eq(parameters['EXECUTE_GITVERSION'], 'True') }}:
        - template: ../../shared/steps/gitversion/setup-gitversion.yml

        - template: ../../shared/steps/gitversion/execute-gitversion.yml

      - template: ../shared/steps/update-project-version.yml
        parameters:
          APPLICATION_VERSION: ${{ parameters.APPLICATION_VERSION }}
          PACKAGE_JSON_FILE_LOCATION: ${{ parameters.PACKAGE_JSON_FILE_LOCATION }}

      - template: ../../shared/steps/docker/docker-build.yml
        parameters:
          CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME: ${{ parameters.CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME }}
          DOCKER_BUILD_ARGS: ${{ parameters.DOCKER_BUILD_ARGS }}
          DOCKER_BUILD_CONTEXT_FOLDER: ${{ parameters.DOCKER_BUILD_CONTEXT_FOLDER }}
          DOCKER_IMAGE_NAME: ${{ parameters.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: ${{ parameters.APPLICATION_VERSION }}
          DOCKER_REGISTRY: ${{ parameters.DOCKER_REGISTRY }}
          DOCKERFILE_PATH: ${{ parameters.DOCKERFILE_PATH }}
          
      - template: ../../shared/steps/docker/docker-push.yml
        parameters:
          CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME: ${{ parameters.CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME }}
          DOCKER_IMAGE_NAME: ${{ parameters.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: ${{ parameters.APPLICATION_VERSION }}
          DOCKER_REGISTRY: ${{ parameters.DOCKER_REGISTRY }}