parameters:
- name: APPLICATION_VERSION
  type: string
  default: $(GitVersion.SemVer)
- name: EXECUTE_GITVERSION
  type: boolean
  default: true
- name: JDK_USED_VERSION
  type: string
  default: $(JAVA_JDK_VERSION)
- name: POM_FILE_LOCATION
  type: string
  default: $(Build.SourcesDirectory)/pom.xml

jobs:
  - job: validate_unit_test_and_sonar_job
    displayName: "Unit Tests and SonarQube"
    pool:
      vmImage: ubuntu-20.04
      demands:
        - java
    steps:
      - template: ../../shared/steps/checkout-repository.yml

      - template: ../shared/steps/use-specific-java-version.yml
        parameters:
          JDK_USED_VERSION: ${{parameters.JDK_USED_VERSION}}

      - ${{ if or(eq(parameters['EXECUTE_GITVERSION'], 'True'), eq(variables['Build.Reason'], 'PullRequest')) }}:
        - template: ../../shared/steps/gitversion/setup-gitversion.yml

        - template: ../../shared/steps/gitversion/execute-gitversion.yml

      - template: ../shared/steps/update-project-version.yml
        parameters:
          APPLICATION_VERSION: ${{ parameters.APPLICATION_VERSION }}
          POM_FILE_LOCATION: ${{ parameters.POM_FILE_LOCATION }}

      - template: ../shared/steps/sonar-cloud-prepare.yml

      - template: ../shared/steps/maven-test.yml

      - template: ../shared/steps/maven-build-and-scan-sonar.yml

      - template: ../../shared/steps/sonar/sonar-publish.yml

      - template: ../../shared/steps/sonar/sonar-build-breaker.yml