parameters:
- name: APPLICATION_VERSION
  type: string
  default: $(GitVersion.SemVer)
- name: DOTNET_USED_VERSION
  type: string
  default: $(DOTNET_SDK_VERSION)
- name: EXECUTE_GITVERSION
  type: boolean
  default: true
- name: SONAR_CLOUD_ORGANIZATION
  type: string
  default: ''
- name: SONAR_CLOUD_SERVICE_CONNECTION_NAME
  type: string
  default: ''
- name: SONAR_EXCLUSIONS
  type: string
  default: '$(SONAR_EXCLUSIONS)'
- name: SONAR_PROJECT_KEY
  type: string
  default: $(SONAR_PROJECT_KEY)
- name: SONAR_PROJECT_NAME
  type: string
  default: $(SONAR_PROJECT_NAME)
- name: VM_IMAGE
  type: string
  default: ''

jobs:
  - job: unit_test_and_sonar_cloud_job
    displayName: "Unit Tests and SonarQube"
    pool:
      vmImage: ${{ parameters.VM_IMAGE }}
      demands:
        - java
    steps:
      - template: ../../shared/steps/checkout-repository.yml

      - template: ../shared/steps/use-specific-dotnet-version.yml
        parameters:
          DOTNET_USED_VERSION: ${{parameters.DOTNET_USED_VERSION}}

      - ${{ if or(eq(parameters['EXECUTE_GITVERSION'], 'True'), eq(variables['Build.Reason'], 'PullRequest')) }}:
        - template: ../../shared/steps/gitversion/setup-gitversion.yml

        - template: ../../shared/steps/gitversion/execute-gitversion.yml

      - template: ../shared/steps/sonar-cloud-prepare.yml
        parameters:
          SONAR_CLOUD_ORGANIZATION: ${{ parameters.SONAR_CLOUD_ORGANIZATION }}
          SONAR_CLOUD_SERVICE_CONNECTION_NAME: ${{ parameters.SONAR_CLOUD_SERVICE_CONNECTION_NAME }}
          SONAR_PROJECT_KEY: ${{ parameters.SONAR_PROJECT_KEY }}
          SONAR_PROJECT_NAME: ${{ parameters.SONAR_PROJECT_NAME }}
          SONAR_EXCLUSIONS: ${{ parameters.SONAR_EXCLUSIONS }}

      - template: ../shared/steps/dotnet-restore.yml

      - template: ../shared/steps/dotnet-build.yml
        parameters:
          APPLICATION_VERSION: ${{parameters.APPLICATION_VERSION}}
          BUILD_REASON: '[SonarCloud]'      

      - template: ../shared/steps/dotnet-test.yml

      - template: ../../shared/steps/sonar/sonar-analyze.yml

      - template: ../../shared/steps/sonar/sonar-cloud-publish.yml

      - template: ../../shared/steps/sonar/sonar-cloud-build-breaker.yml
        parameters:
          SONAR_CLOUD_ORGANIZATION: ${{ parameters.SONAR_CLOUD_ORGANIZATION }}
          SONAR_CLOUD_SERVICE_CONNECTION_NAME: ${{ parameters.SONAR_CLOUD_SERVICE_CONNECTION_NAME }}