parameters:
- name: APPLICATION_VERSION
  type: string
  default: $(GitVersion.SemVer)
- name: CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME
  type: string
  default: 'DockerHub'
- name: DOCKER_BUILD_ARGS
  type: string
  default: '' #Exemplo: --build-arg FIRST_ARG=FIRST_ARG_VALUE --build-arg SECOND_ARG=SECOND_ARG_VALUE
- name: DOCKER_BUILD_CONTEXT_FOLDER
  type: string
  default: '$(Build.SourcesDirectory)'
- name: DOCKER_IMAGE_NAME
  type: string
  default: ''
- name: DOCKER_IMAGE_TAG
  type: string
  default: ''
- name: DOCKER_REGISTRY
  type: string
  default: 'gladsonbruno'
- name: DOCKERFILE_PATH
  type: string
  default: '$(Build.SourcesDirectory)/Dockerfile'
- name: DOTNET_USED_VERSION
  type: string
  default: $(DOTNET_SDK_VERSION)
- name: EXECUTE_GITVERSION
  type: boolean
  default: true
- name: SONAR_CLOUD_ORGANIZATION
  type: string
  default: 'portifoliogladson'
- name: SONAR_CLOUD_SERVICE_CONNECTION_NAME
  type: string
  default: 'SonarCloud'
- name: SONAR_EXCLUSIONS
  type: string
  default: '$(SONAR_EXCLUSIONS)'
- name: SONAR_PROJECT_KEY
  type: string
  default: $(SONAR_PROJECT_KEY)
- name: SONAR_PROJECT_NAME
  type: string
  default: $(SONAR_PROJECT_NAME)
- name: VM_IMAGE
  type: string
  default: 'ubuntu-20.04'

stages:
  - stage: validations_stage
    displayName: "Validations"
    condition: | 
      or(
        eq(variables['Build.Reason'], 'PullRequest'),
        and(
          ne(variables['Build.Reason'], 'PullRequest'),
          or(
            eq(variables['Build.SourceBranchName'], 'master'),
            eq(variables['Build.SourceBranchName'], 'develop')
          )
        )
      )
    variables:
      APPLICATION_VERSION: ${{ parameters.APPLICATION_VERSION }}
    jobs: 
      - template: ./jobs/validations-job.yml
        parameters:
          APPLICATION_VERSION: $(APPLICATION_VERSION)
          DOTNET_USED_VERSION: ${{ parameters.DOTNET_USED_VERSION }}
          EXECUTE_GITVERSION: true
          SONAR_CLOUD_ORGANIZATION: ${{ parameters.SONAR_CLOUD_ORGANIZATION }}
          SONAR_CLOUD_SERVICE_CONNECTION_NAME: ${{ parameters.SONAR_CLOUD_SERVICE_CONNECTION_NAME }}
          VM_IMAGE: ${{ parameters.VM_IMAGE }}

  - stage: build_stage
    displayName: "Build"
    dependsOn: [ "validations_stage" ]
    condition: or(
      eq(variables['Build.SourceBranchName'], 'master'),
      eq(variables['Build.SourceBranchName'], 'develop')
      )
    variables:
      APPLICATION_VERSION: $[ stageDependencies.validations_stage.unit_test_and_sonar_cloud_job.outputs['gitversion.VERSION'] ]
    jobs: 
      - template: ./jobs/build-job.yml
        parameters:
          APPLICATION_VERSION: $(APPLICATION_VERSION)
          CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME: ${{ parameters.CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME }}
          DOCKER_IMAGE_NAME: ${{ parameters.DOCKER_IMAGE_NAME }}
          DOCKER_BUILD_ARGS: ${{ parameters.DOCKER_BUILD_ARGS }}
          DOCKER_BUILD_CONTEXT_FOLDER: ${{ parameters.DOCKER_BUILD_CONTEXT_FOLDER }}
          DOCKERFILE_PATH: ${{ parameters.DOCKERFILE_PATH }}
          DOCKER_REGISTRY: ${{ parameters.DOCKER_REGISTRY }}
          EXECUTE_GITVERSION: false
          VM_IMAGE: ${{ parameters.VM_IMAGE }}

      - template: ../shared/jobs/trivy/check-container-vulnerabilities.yml
        parameters:
          CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME: ${{ parameters.CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME }}
          DEPENDS_ON: [ build_job ]
          DOCKER_IMAGE_NAME: ${{ parameters.DOCKER_IMAGE_NAME }}
          DOCKER_IMAGE_TAG: $(APPLICATION_VERSION)
          DOCKER_REGISTRY: ${{ parameters.DOCKER_REGISTRY }}
          VM_IMAGE: ${{ parameters.VM_IMAGE }}