parameters:
- name: CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME
  type: string
  default: ''
steps:
  - task: Docker@2
    displayName: 'Docker Logout'
    inputs:
      containerRegistry: ${{parameters.CONTAINER_REGISTRY_SERVICE_CONNECTION_NAME}}
      command: 'logout'      